export const categories = [
  {
    id: 'jedzenie',
    name: 'Jedzenie',
    emoji: '🍕',
    description: 'Smaczne tematy, ale powiedz źle i jesteś spalony!',
    color: 'bg-gradient-to-br from-orange-400 to-red-500',
    words: [
      { word: 'pizza', hints: ['włochy', 'ser', 'ciasto', 'kawałek'] },
      { word: 'burger', hints: ['bułka', 'mięso', 'fast food', 'sałata'] },
      { word: 'sushi', hints: ['ryba', 'ryż', 'japonia', 'pałeczki'] },
      { word: 'lody', hints: ['zimne', 'deser', 'lato', 'rożek'] },
      { word: 'czekolada', hints: ['kakao', 'słodkie', 'tabliczka', 'deserek'] },
      { word: 'makaron', hints: ['włochy', 'ugotowany', 'nitki', 'sos'] },
      { word: 'tort', hints: ['urodziny', 'świeczki', 'krem', 'kawałki'] },
      { word: 'kebab', hints: ['turecki', 'mięso', 'bułka', 'sos'] },
      { word: 'frytki', hints: ['ziemniaki', 'smażone', 'ketchup', 'fast food'] },
      { word: 'kurczak', hints: ['mięso', 'skrzydełka', 'pieczony', 'KFC'] },
    ]
  },
  {
    id: 'zwierzeta',
    name: 'Zwierzęta',
    emoji: '🦁',
    description: 'Od psów po dzikie bestie... Nie pomyl ich!',
    color: 'bg-gradient-to-br from-green-400 to-emerald-600',
    words: [
      { word: 'krowa', hints: ['mleko', 'wieś', 'rogi', 'łąka'] },
      { word: 'koń', hints: ['jeździectwo', 'grzywa', 'galop', 'siodło'] },
      { word: 'pies', hints: ['szczeka', 'smycz', 'łapy', 'przyjaciel'] },
      { word: 'kot', hints: ['mruczy', 'wąsy', 'pazury', 'miauczy'] },
      { word: 'słoń', hints: ['trąba', 'afryka', 'duży', 'uszy'] },
      { word: 'lew', hints: ['król', 'grzywa', 'safari', 'ryczy'] },
      { word: 'żyrafa', hints: ['szyja', 'wysoka', 'plamy', 'afryka'] },
      { word: 'pingwin', hints: ['antarktyda', 'smoking', 'lód', 'ryby'] },
      { word: 'delfin', hints: ['ocean', 'inteligentny', 'płetwa', 'skacze'] },
      { word: 'kangur', hints: ['australia', 'torba', 'skacze', 'boks'] },
    ]
  },
  {
    id: 'celebryci',
    name: 'Celebryci',
    emoji: '⭐',
    description: 'Znane nazwiska z filmów, muzyki i świata! Czy je znasz?',
    color: 'bg-gradient-to-br from-pink-400 to-purple-600',
    words: [
      { word: 'Beyoncé', hints: ['piosenkarka', 'diva', 'jay-z', 'single ladies'] },
      { word: 'Ronaldo', hints: ['piłkarz', 'portugalia', 'CR7', 'celebryta'] },
      { word: 'Elon Musk', hints: ['tesla', 'rakiety', 'twitter', 'miliarder'] },
      { word: 'Taylor Swift', hints: ['piosenkarka', 'country', 'koncerty', 'świat'] },
      { word: 'Kim Kardashian', hints: ['reality show', 'moda', 'celebrytka', 'instagram'] },
      { word: 'Dwayne Johnson', hints: ['skała', 'zapaśnik', 'aktor', 'mięśnie'] },
      { word: 'Rihanna', hints: ['piosenkarka', 'umbrella', 'kosmetyki', 'barbados'] },
      { word: 'Messi', hints: ['piłkarz', 'argentyna', 'barcelona', 'geniusz'] },
      { word: 'Oprah', hints: ['talk show', 'miliarderka', 'książki', 'usa'] },
      { word: 'Will Smith', hints: ['aktor', 'oscar', 'rap', 'filmowy'] },
    ]
  },
  {
    id: 'hollywood',
    name: 'Hollywood',
    emoji: '🎬',
    description: 'Lustra znalezione za kamerami i podziałami na baśniach!',
    color: 'bg-gradient-to-br from-yellow-400 to-amber-600',
    words: [
      { word: 'Oscar', hints: ['nagroda', 'złota', 'statuetka', 'film'] },
      { word: 'reżyser', hints: ['kamera', 'akcja', 'film', 'krzesło'] },
      { word: 'trailer', hints: ['zapowiedź', 'kino', 'minuty', 'reklama'] },
      { word: 'aktor', hints: ['gra', 'rola', 'scena', 'kamera'] },
      { word: 'Batman', hints: ['superbohater', 'nietoperz', 'gotham', 'kostium'] },
      { word: 'Star Wars', hints: ['gwiezdne', 'miecz', 'kosmos', 'saga'] },
      { word: 'kaskader', hints: ['niebezpieczny', 'skok', 'dubel', 'akcja'] },
      { word: 'scenariusz', hints: ['tekst', 'dialog', 'historia', 'pisany'] },
      { word: 'premier', hints: ['otwarcie', 'czerwony dywan', 'pierwszy', 'uroczyste'] },
      { word: 'sequel', hints: ['kontynuacja', 'część druga', 'następny', 'franchise'] },
    ]
  },
  {
    id: 'zawody',
    name: 'Zawody',
    emoji: '👨‍⚕️',
    description: 'Czym zajmujesz się zawodowo? Zgadnij zanim będzie za późno!',
    color: 'bg-gradient-to-br from-blue-400 to-indigo-600',
    words: [
      { word: 'lekarz', hints: ['szpital', 'biały fartuch', 'leczy', 'stetoskop'] },
      { word: 'nauczyciel', hints: ['szkoła', 'tablica', 'uczy', 'dzieci'] },
      { word: 'kucharz', hints: ['gotuje', 'restauracja', 'czapka', 'smak'] },
      { word: 'policjant', hints: ['mundur', 'prawo', 'patrol', 'kajdanki'] },
      { word: 'strażak', hints: ['wóz', 'pożar', 'woda', 'bohater'] },
      { word: 'pilot', hints: ['samolot', 'lata', 'kokpit', 'niebo'] },
      { word: 'programista', hints: ['komputer', 'kod', 'bug', 'klawiatura'] },
      { word: 'fryzjer', hints: ['nożyczki', 'włosy', 'salon', 'strzyże'] },
      { word: 'mechanik', hints: ['samochód', 'naprawa', 'klucz', 'warsztat'] },
      { word: 'dentista', hints: ['zęby', 'wiertło', 'gabinet', 'ból'] },
    ]
  },
  {
    id: 'hobby',
    name: 'Hobby',
    emoji: '🎨',
    description: 'Co lubisz robić w wolnym czasie? Pokaż swoją pasję!',
    color: 'bg-gradient-to-br from-cyan-400 to-teal-600',
    words: [
      { word: 'fotografia', hints: ['aparat', 'zdjęcia', 'obiektyw', 'kadr'] },
      { word: 'gotowanie', hints: ['kuchnia', 'przepis', 'smak', 'garnek'] },
      { word: 'malowanie', hints: ['pędzel', 'farby', 'obraz', 'płótno'] },
      { word: 'śpiew', hints: ['głos', 'mikrofon', 'melodia', 'nuty'] },
      { word: 'taniec', hints: ['muzyka', 'ruch', 'rytm', 'parkiet'] },
      { word: 'czytanie', hints: ['książka', 'strony', 'historia', 'biblioteka'] },
      { word: 'gry wideo', hints: ['konsola', 'joystick', 'ekran', 'level'] },
      { word: 'bieganie', hints: ['sport', 'buty', 'trasa', 'maraton'] },
      { word: 'yoga', hints: ['mata', 'pozycje', 'spokój', 'medytacja'] },
      { word: 'ogrodnictwo', hints: ['rośliny', 'ziemia', 'narzędzia', 'kwiaty'] },
    ]
  },
  {
    id: 'marki',
    name: 'Marki',
    emoji: '🏷️',
    description: 'Znane logo i sławne firmy... Czy rozpoznasz je wszystkie?',
    color: 'bg-gradient-to-br from-red-400 to-rose-600',
    words: [
      { word: 'Apple', hints: ['jabłko', 'iPhone', 'mac', 'technologia'] },
      { word: 'Nike', hints: ['swoosh', 'buty', 'sport', 'just do it'] },
      { word: 'McDonald\'s', hints: ['złote łuki', 'burger', 'fast food', 'Ronald'] },
      { word: 'Coca-Cola', hints: ['czerwony', 'napój', 'bąbelki', 'klasyka'] },
      { word: 'Adidas', hints: ['trzy paski', 'sport', 'buty', 'dres'] },
      { word: 'Google', hints: ['wyszukiwarka', 'internet', 'kolorowe', 'technologia'] },
      { word: 'Netflix', hints: ['streaming', 'filmy', 'seriale', 'N'] },
      { word: 'IKEA', hints: ['meble', 'szwecja', 'składane', 'niebieski'] },
      { word: 'Starbucks', hints: ['kawa', 'zielony', 'kubek', 'syrena'] },
      { word: 'LEGO', hints: ['klocki', 'budowanie', 'kolorowe', 'dania'] },
    ]
  },
  {
    id: 'rodzina',
    name: 'Rodzina',
    emoji: '👨‍👩‍👧‍👦',
    description: 'Kto jest kim w rodzinie? Miej oko na impostora!',
    color: 'bg-gradient-to-br from-violet-400 to-fuchsia-600',
    words: [
      { word: 'mama', hints: ['rodzic', 'kobieta', 'miłość', 'dom'] },
      { word: 'tata', hints: ['rodzic', 'mężczyzna', 'silny', 'dom'] },
      { word: 'babcia', hints: ['starsze pokolenie', 'ciasta', 'mądra', 'kochana'] },
      { word: 'dziadek', hints: ['starsze pokolenie', 'mądry', 'doświadczony', 'opowieści'] },
      { word: 'siostra', hints: ['rodzeństwo', 'dziewczyna', 'pokój', 'kłótnie'] },
      { word: 'brat', hints: ['rodzeństwo', 'chłopak', 'zabawa', 'przyjaciel'] },
      { word: 'ciocia', hints: ['siostra rodzica', 'prezenty', 'odwiedziny', 'rodzina'] },
      { word: 'wujek', hints: ['brat rodzica', 'żarty', 'rodzina', 'odwiedziny'] },
      { word: 'kuzyn', hints: ['dziecko wujka', 'rodzina', 'święta', 'zabawa'] },
      { word: 'córka', hints: ['dziewczynka', 'dziecko', 'rodzic', 'miłość'] },
    ]
  },
  {
    id: 'postacie',
    name: 'Postacie',
    emoji: '🦸',
    description: 'Bohaterowie z bajek i filmów czekają... Zgadnij ich!',
    color: 'bg-gradient-to-br from-lime-400 to-green-600',
    words: [
      { word: 'Superman', hints: ['peleryna', 'lata', 'S', 'kryptonit'] },
      { word: 'Harry Potter', hints: ['czarodziej', 'blizna', 'różdżka', 'Hogwart'] },
      { word: 'Mickey Mouse', hints: ['myszka', 'Disney', 'okrągłe uszy', 'kreskówka'] },
      { word: 'Shrek', hints: ['ogr', 'zielony', 'bajka', 'osioł'] },
      { word: 'SpongeBob', hints: ['gąbka', 'ocean', 'żółty', 'krab'] },
      { word: 'Elsa', hints: ['Frozen', 'królowa', 'lód', 'Let it go'] },
      { word: 'Pikachu', hints: ['Pokemon', 'żółty', 'elektryczny', 'Pika'] },
      { word: 'Mario', hints: ['hydraulik', 'wąsy', 'Nintendo', 'grzyb'] },
      { word: 'Joker', hints: ['wróg Batmana', 'uśmiech', 'szalony', 'karty'] },
      { word: 'Yoda', hints: ['Star Wars', 'zielony', 'mały', 'mądry'] },
    ]
  },
  {
    id: 'natura',
    name: 'Natura',
    emoji: '🏔️',
    description: 'Od gór po oceany... Odkryj cuda natury!',
    color: 'bg-gradient-to-br from-emerald-400 to-green-700',
    words: [
      { word: 'góra', hints: ['wysoka', 'szczyt', 'wspinaczka', 'widok'] },
      { word: 'ocean', hints: ['woda', 'słony', 'ogromny', 'fale'] },
      { word: 'las', hints: ['drzewa', 'zielony', 'grzyby', 'ścieżka'] },
      { word: 'pustynia', hints: ['piasek', 'gorąco', 'sucha', 'kaktusy'] },
      { word: 'wodospad', hints: ['woda', 'spada', 'hałas', 'piękny'] },
      { word: 'wulkan', hints: ['lawa', 'wybuch', 'góra', 'gorący'] },
      { word: 'plaża', hints: ['piasek', 'morze', 'lato', 'parasol'] },
      { word: 'jaskinia', hints: ['ciemna', 'nietoperze', 'skała', 'grota'] },
      { word: 'wyspa', hints: ['woda dookoła', 'tropikalna', 'palmy', 'odizolowana'] },
      { word: 'rzeka', hints: ['płynie', 'woda', 'most', 'brzeg'] },
    ]
  },
  {
    id: 'miejsca',
    name: 'Popularne miejsca',
    emoji: '🗽',
    description: 'Podróżuj po świecie i odkryj ikoniczne miejsca!',
    color: 'bg-gradient-to-br from-sky-400 to-blue-600',
    words: [
      { word: 'Paryż', hints: ['Francja', 'wieża', 'stolica', 'romantyczny'] },
      { word: 'Nowy Jork', hints: ['USA', 'Manhattan', 'statua wolności', 'big apple'] },
      { word: 'Tokio', hints: ['Japonia', 'neon', 'technologia', 'stolica'] },
      { word: 'Egipt', hints: ['piramidy', 'Sfinks', 'faraon', 'Nil'] },
      { word: 'Wenecja', hints: ['Włochy', 'gondole', 'kanały', 'woda'] },
      { word: 'Las Vegas', hints: ['USA', 'kasyno', 'pustyna', 'hazard'] },
      { word: 'Disneyland', hints: ['park', 'Mickey', 'zamek', 'dzieci'] },
      { word: 'Wielki Mur', hints: ['Chiny', 'długi', 'historyczny', 'obrona'] },
      { word: 'Mount Everest', hints: ['najwyższy', 'Himalaje', 'śnieg', 'wspinaczka'] },
      { word: 'Amazonia', hints: ['las deszczowy', 'rzeka', 'dżungla', 'największa'] },
    ]
  },
  {
    id: 'sport',
    name: 'Sport',
    emoji: '⚽',
    description: 'Odgrywaj swoje ulubione dyscypliny sportowe!',
    color: 'bg-gradient-to-br from-orange-400 to-red-600',
    words: [
      { word: 'piłka nożna', hints: ['bramka', 'mundial', 'kopie', 'boisko'] },
      { word: 'koszykówka', hints: ['kosz', 'NBA', 'wysoki', 'odbija'] },
      { word: 'tenis', hints: ['rakieta', 'kort', 'piłka', 'Wimbledon'] },
      { word: 'pływanie', hints: ['basen', 'woda', 'styl', 'okularki'] },
      { word: 'boks', hints: ['rękawice', 'ring', 'pięści', 'knockaut'] },
      { word: 'golf', hints: ['kij', 'piłka', 'dołek', 'pole'] },
      { word: 'siatkówka', hints: ['siatka', 'plaża', 'serwis', 'zespołowa'] },
      { word: 'hokej', hints: ['lód', 'kij', 'krążek', 'bramka'] },
      { word: 'formuła 1', hints: ['wyścig', 'bolid', 'szybkość', 'tor'] },
      { word: 'rugby', hints: ['owalny', 'kontakt', 'zespołowa', 'wytrzymałość'] },
    ]
  },
];
